<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>nbp-pms-api-secrets</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nbp.Pms.Application\Nbp.Pms.Application.csproj" />
    <ProjectReference Include="..\Nbp.Pms.Infrastructure\Nbp.Pms.Infrastructure.csproj" />
    <ProjectReference Include="..\Nbp.Pms.Contracts\Nbp.Pms.Contracts.csproj" />
    <ProjectReference Include="..\Nbp.Pms.BackgroundJobs\Nbp.Pms.BackgroundJobs.csproj" />
  </ItemGroup>
</Project>
